export const DETAIL_UPDATE_LIST = 'DETAIL_UPDATE_LIST';
export const DETAIL_UPDATE_ITEM = 'DETAIL_UPDATE_ITEM';
export const DETAIL_SET_FETCHING = 'DETAIL_SET_FETCHING';
export const DETAIL_UPDATE_OFFSET = 'DETAIL_UPDATE_OFFSET';