export const DETAIL_UPDATE_ITEM = 'DETAIL_UPDATE_ITEM';
export const DETAIL_SET_FETCHING = 'DETAIL_SET_FETCHING';
export const DETAIL_UPDATE_OFFSET = 'DETAIL_UPDATE_OFFSET';
export const DETAIL_UPDATE_MESSAGE = 'DETAIL_UPDATE_MESSAGE'