export const POKE_UPDATE_LIST = 'POKE_UPDATE_LIST';
export const POKE_UPDATE_ITEM = 'POKE_UPDATE_ITEM';
export const POKE_SET_FETCHING = 'POKE_SET_FETCHING';
export const POKE_UPDATE_OFFSET = 'POKE_UPDATE_OFFSET'